### ISSUE TITLE
Mobile scrolling

### ISSUE THREAD

**Issue by mrelevo** [rehman553/pve#16]
On mobile devices, scrolling back up once you've past the intro animation and you come to the main title "Interrupting the Journey to Extremism" seems almost impossible. Sometimes you can scroll back up. sometimes you cannot. User should be able to scroll back up to the top at anytime

![image](https://user-images.githubusercontent.com/10246056/215632983-7900eb97-3c54-4788-9d29-15c87046ef03.png)

**Comment by rehman553** [comment]
I check this issue, Yes it is happening, actually we need to play with 2 scrolls to show the white site area fixed after the animation and getting back to the animation could be difficult if user swipe a little, on a bit longer swipe it will work fine 

I am looking into it, My be we need to skip that fixed  style after the animation for batter access.

**Comment by mrelevo** [comment]
@rehman553 also on mobile (iphone/safari) i cannot scroll further down past the title Interrupting the Journey to Extremism

**Comment by rehman553** [comment]
Yes I am checking this issue i guess phone devices taking the whole viewport as scroll, I am figuring it out.

**Comment by rehman553** [comment]
I update the top side animation to more smoother, working fine now 

and skip the main section fixed effect, i try multiple  options but the mobile devices always has different may be it is due to extra easing effect.
